config/routes.rb
Toxls::Application.routes.draw do
  resources :emps

  match 'export_emp_details' => "emps#export_emp_details", :as => "export_emp_details"  

  root :to => 'emps#index'

end

app/models/email.rb
class Email < ActiveRecord::Base
  attr_accessible :email, :user_id
  belongs_to :emp

  def email_name
  	self.email
  end
end

app/models/emp.rb
class Emp < ActiveRecord::Base
  attr_accessible :first_name, :last_name
  has_one :email

  def full_name
  	"#{self.first_name} #{self.last_name}"  	
  end

end

app/models/users.rb
class Users < ActiveRecord::Base
  # attr_accessible :title, :body
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/emps_controller.rb
class EmpsController < ApplicationController
  # GET /emps
  # GET /emps.json
  def index
    @emps = Emp.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @emps }
    end
  end

  # GET /emps/1
  # GET /emps/1.json
  def show
    @emp = Emp.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @emp }
    end
  end

  # GET /emps/new
  # GET /emps/new.json
  def new
    @emp = Emp.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @emp }
    end
  end

  # GET /emps/1/edit
  def edit
    @emp = Emp.find(params[:id])
  end

  # POST /emps
  # POST /emps.json
  def create
    @emp = Emp.new(params[:emp])

    respond_to do |format|
      if @emp.save
        format.html { redirect_to @emp, notice: 'Emp was successfully created.' }
        format.json { render json: @emp, status: :created, location: @emp }
      else
        format.html { render action: "new" }
        format.json { render json: @emp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /emps/1
  # PUT /emps/1.json
  def update
    @emp = Emp.find(params[:id])

    respond_to do |format|
      if @emp.update_attributes(params[:emp])
        format.html { redirect_to @emp, notice: 'Emp was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @emp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emps/1
  # DELETE /emps/1.json
  def destroy
    @emp = Emp.find(params[:id])
    @emp.destroy

    respond_to do |format|
      format.html { redirect_to emps_url }
      format.json { head :no_content }
    end
  end

  def export_emp_details
    @emps = Emp.all
    respond_to do |format|      
      format.xls { 
       send_data @emps.to_xls(:headers => ["First Name", "Last Name", "Full Name", "Email"], :columns => [:first_name, :last_name, :full_name, {:email => :email_name} ], :cell_format => {:color => :blue}, :header_format => {:weight => :bold}), :filename => 'emp_details.xls' 
      }      
    end    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.first
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emps_helper.rb
module EmpsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/emps/_form.html.erb
<%= form_for(@emp) do |f| %>
  <% if @emp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@emp.errors.count, "error") %> prohibited this emp from being saved:</h2>

      <ul>
      <% @emp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/emps/edit.html.erb
<h1>Editing emp</h1>

<%= render 'form' %>

<%= link_to 'Show', @emp %> |
<%= link_to 'Back', emps_path %>

app/views/emps/index.html.erb
<h1>Listing emps</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @emps.each do |emp| %>
  <tr>
    <td><%= emp.first_name %></td>
    <td><%= emp.last_name %></td>
    <td><%= link_to 'Show', emp %></td>
    <td><%= link_to 'Edit', edit_emp_path(emp) %></td>
    <td><%= link_to 'Destroy', emp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Emp', new_emp_path %>
<%= link_to 'Export Emp Details', export_emp_details_path(:format => 'xls') %>

app/views/emps/new.html.erb
<h1>New emp</h1>

<%= render 'form' %>

<%= link_to 'Back', emps_path %>

app/views/emps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @emp.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @emp.last_name %>
</p>


<%= link_to 'Edit', edit_emp_path(@emp) %> |
<%= link_to 'Back', emps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Toxls</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>